import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import { Navbar } from "./components/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import ServiceCard from "./components/serviceCard";


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Adjust weights as needed
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
       className={`${roboto.className}antialiased`}
       
      >
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
